name: Check branch is rebased
on:
  merge_group:
  pull_request:
    branches:
      - main

jobs:
  check-rebased:
      runs-on: ubuntu-latest
      if: github.event_name != 'merge_group'
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: check rebased
          run: |
            git fetch origin
            git checkout main
            git merge origin/${{ github.head_ref }} --ff-only
