name: Push in main
on:
  push:
    branches:
      - main

jobs:
  push-in-main:
    runs-on: ubuntu-latest
    steps:
      - run: |
          PR_BRANCHES=$(gh pr list --base main --json 'headRefName' --jq .[].headRefName)
          for BRANCH in $PR_BRANCHES; do
              RUN=$(gh run list --branch $BRANCH -w "Check branch is rebased" --json databaseId)
              gh run rerun $RUN
