name: Sign and rebase
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  rebase:
    env:
      GH_TOKEN: ${{ github.token  }}
    name: Sign and rebase
    runs-on: ubuntu-latest
    if: >-
      github.event.issue.pull_request != '' &&
      (
        contains(github.event.comment.body, '/sign-and-rebase') ||
        contains(github.event.comment.body, '/autosquash')
      )
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v4
      - name: Sign and rebase
        run: |
          gh pr update-branch --rebase ${{ github.event.issue.number  }}
          #git config user.name github-actions
          #git config user.email github-actions@github.com
          #gh pr checkout ${{ github.event.issue.number  }}
          #git rebase -f --gpg-sign --autosquash origin/main
          #git push -f
